// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF9PwBbgdwR5FtXz5Z-XykhdxocGK6ogU',
    appId: '1:290377575854:web:543b332ab815548a7aac3f',
    messagingSenderId: '290377575854',
    projectId: 'careers-portal-3fd21',
    authDomain: 'careers-portal-3fd21.firebaseapp.com',
    storageBucket: 'careers-portal-3fd21.appspot.com',
    measurementId: 'G-JNMP1J4269',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOPvpofBrrQxXmTElZv-MkODq_ldgg4mE',
    appId: '1:290377575854:android:28cdfab418530e157aac3f',
    messagingSenderId: '290377575854',
    projectId: 'careers-portal-3fd21',
    storageBucket: 'careers-portal-3fd21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZ_KIP4zyv0l7JlXA1nZgEzK0WZ9etJA',
    appId: '1:290377575854:ios:51ab284d49a4f88a7aac3f',
    messagingSenderId: '290377575854',
    projectId: 'careers-portal-3fd21',
    storageBucket: 'careers-portal-3fd21.appspot.com',
    iosBundleId: 'com.example.careerPortal',
  );
}
